/**
 * Sound, synthesised. No files, no loading, no CDN.
 *
 * The sandbox has no audio assets and fetching them is a gamble on a url, so
 * every sound here is generated by the Web Audio API at the moment it plays.
 * That is not a compromise: oscillators and filtered noise are exactly what
 * arcade sound effects are, and they cost nothing and never fail to load.
 *
 * Browsers refuse to start audio before the player has interacted with the
 * page — an unavoidable rule, and the reason a game that "has no sound" usually
 * just never got a gesture. This unlocks itself on the first click, tap or key,
 * so a game never has to think about it.
 *
 *   const audio = createAudio()
 *   audio.play("coin")
 *   audio.tone({ frequency: 440, duration: 0.2 })
 */
export function createAudio(options = {}) {
  const { volume = 0.35 } = options

  let context = null
  let master = null
  let musicGain = null
  let unlocked = false
  let currentVolume = volume
  // Multiplies every note scheduled while a named sound is playing. Sound
  // factories call `tone` synchronously, so setting this around the call is
  // enough to pitch a whole effect without threading an argument through each.
  let pitchShift = 1

  function ensure() {
    if (context) return context
    const Context = window.AudioContext ?? window.webkitAudioContext
    if (!Context) return null
    context = new Context()
    master = context.createGain()
    master.gain.value = currentVolume
    master.connect(context.destination)
    musicGain = context.createGain()
    musicGain.gain.value = 0.5
    musicGain.connect(master)
    return context
  }

  function unlock() {
    const ctx = ensure()
    if (!ctx) return
    if (ctx.state === "suspended") ctx.resume()
    unlocked = true
  }

  for (const event of ["pointerdown", "keydown", "touchstart"]) {
    window.addEventListener(event, unlock, { once: false, passive: true })
  }

  function now() {
    return context ? context.currentTime : 0
  }

  /**
   * One note. `slide` bends the pitch over the note's life, which is the whole
   * difference between a beep and a jump, a laser or a power-up.
   */
  function tone(config = {}) {
    const ctx = ensure()
    if (!ctx || audio.muted) return
    const {
      frequency = 440,
      type = "square",
      duration = 0.15,
      gain = 0.3,
      slide = 0,
      attack = 0.005,
      delay = 0,
      destination = master,
    } = config

    const start = now() + delay
    const pitched = frequency * pitchShift
    const oscillator = ctx.createOscillator()
    const envelope = ctx.createGain()

    oscillator.type = type
    oscillator.frequency.setValueAtTime(pitched, start)
    if (slide) {
      // Exponential, not linear: pitch is perceived logarithmically, so a
      // linear ramp sounds like it slows down as it falls.
      oscillator.frequency.exponentialRampToValueAtTime(
        Math.max(1, pitched + slide * pitchShift),
        start + duration
      )
    }

    // A hard start or stop is an audible click — the envelope is not optional.
    envelope.gain.setValueAtTime(0.0001, start)
    envelope.gain.exponentialRampToValueAtTime(gain, start + attack)
    envelope.gain.exponentialRampToValueAtTime(0.0001, start + duration)

    oscillator.connect(envelope)
    envelope.connect(destination)
    oscillator.start(start)
    oscillator.stop(start + duration + 0.02)
    return oscillator
  }

  /** Filtered white noise: explosions, footsteps, wind, hits, engine rumble. */
  function noise(config = {}) {
    const ctx = ensure()
    if (!ctx || audio.muted) return
    const {
      duration = 0.3,
      gain = 0.3,
      frequency = 1200,
      type = "lowpass",
      sweep = 0,
      Q = 1,
      delay = 0,
    } = config

    const start = now() + delay
    const frames = Math.max(1, Math.floor(ctx.sampleRate * duration))
    const buffer = ctx.createBuffer(1, frames, ctx.sampleRate)
    const data = buffer.getChannelData(0)
    for (let i = 0; i < frames; i++) data[i] = Math.random() * 2 - 1

    const source = ctx.createBufferSource()
    source.buffer = buffer

    const filter = ctx.createBiquadFilter()
    filter.type = type
    filter.frequency.setValueAtTime(frequency, start)
    filter.Q.value = Q
    if (sweep) {
      filter.frequency.exponentialRampToValueAtTime(
        Math.max(40, frequency + sweep),
        start + duration
      )
    }

    const envelope = ctx.createGain()
    envelope.gain.setValueAtTime(gain, start)
    envelope.gain.exponentialRampToValueAtTime(0.0001, start + duration)

    source.connect(filter)
    filter.connect(envelope)
    envelope.connect(master)
    source.start(start)
    return source
  }

  /**
   * A named sound. These are the vocabulary most games need, tuned so they sit
   * together — nothing here is louder or brighter than the rest by accident.
   */
  const sounds = {
    click: () =>
      tone({ frequency: 900, type: "square", duration: 0.04, gain: 0.14 }),
    blip: () =>
      tone({ frequency: 620, type: "square", duration: 0.07, gain: 0.2 }),
    select: () => {
      tone({ frequency: 520, duration: 0.06, gain: 0.18 })
      tone({ frequency: 780, duration: 0.08, gain: 0.18, delay: 0.05 })
    },
    coin: () => {
      tone({ frequency: 988, type: "square", duration: 0.07, gain: 0.22 })
      tone({
        frequency: 1319,
        type: "square",
        duration: 0.14,
        gain: 0.22,
        delay: 0.06,
      })
    },
    jump: () =>
      tone({
        frequency: 300,
        type: "square",
        duration: 0.16,
        gain: 0.22,
        slide: 420,
      }),
    land: () =>
      noise({ duration: 0.1, frequency: 500, gain: 0.18, sweep: -300 }),
    hit: () => {
      tone({
        frequency: 180,
        type: "sawtooth",
        duration: 0.12,
        gain: 0.28,
        slide: -120,
      })
      noise({ duration: 0.1, frequency: 2400, gain: 0.2, sweep: -1800 })
    },
    hurt: () =>
      tone({
        frequency: 420,
        type: "sawtooth",
        duration: 0.28,
        gain: 0.28,
        slide: -300,
      }),
    laser: () =>
      tone({
        frequency: 1400,
        type: "sawtooth",
        duration: 0.14,
        gain: 0.2,
        slide: -1100,
      }),
    shoot: () => {
      tone({
        frequency: 800,
        type: "square",
        duration: 0.06,
        gain: 0.16,
        slide: -500,
      })
      noise({ duration: 0.08, frequency: 3000, gain: 0.12, sweep: -2000 })
    },
    explosion: () => {
      noise({
        duration: 0.7,
        frequency: 900,
        gain: 0.4,
        sweep: -820,
        type: "lowpass",
      })
      tone({
        frequency: 90,
        type: "sine",
        duration: 0.5,
        gain: 0.3,
        slide: -60,
      })
    },
    powerup: () => {
      const steps = [523, 659, 784, 1047]
      steps.forEach((frequency, i) =>
        tone({
          frequency,
          type: "triangle",
          duration: 0.12,
          gain: 0.2,
          delay: i * 0.07,
        })
      )
    },
    win: () => {
      const fanfare = [523, 659, 784, 1047, 1319]
      fanfare.forEach((frequency, i) =>
        tone({
          frequency,
          type: "triangle",
          duration: 0.28,
          gain: 0.22,
          delay: i * 0.11,
        })
      )
    },
    lose: () => {
      const fall = [440, 370, 294, 220]
      fall.forEach((frequency, i) =>
        tone({
          frequency,
          type: "sawtooth",
          duration: 0.3,
          gain: 0.22,
          delay: i * 0.14,
        })
      )
    },
    step: () =>
      noise({ duration: 0.06, frequency: 900, gain: 0.08, sweep: -400 }),
    whoosh: () =>
      noise({
        duration: 0.3,
        frequency: 400,
        gain: 0.14,
        sweep: 1600,
        type: "bandpass",
        Q: 2,
      }),
    thud: () =>
      tone({
        frequency: 120,
        type: "sine",
        duration: 0.18,
        gain: 0.34,
        slide: -60,
      }),
    alarm: () => {
      tone({ frequency: 740, type: "square", duration: 0.18, gain: 0.2 })
      tone({
        frequency: 620,
        type: "square",
        duration: 0.18,
        gain: 0.2,
        delay: 0.2,
      })
    },
  }

  // --- Music ----------------------------------------------------------------

  let musicTimer = null

  /**
   * A looping arpeggio over a chord progression. Not a soundtrack, but a bed
   * of sound underneath the game, which is most of what background music does.
   */
  function startMusic(config = {}) {
    const {
      notes = [220, 277, 330, 440, 330, 277],
      tempo = 240,
      type = "triangle",
      gain = 0.08,
    } = config
    stopMusic()
    ensure()
    let step = 0
    const interval = 60000 / tempo
    musicTimer = setInterval(() => {
      if (audio.muted || !unlocked) return
      tone({
        frequency: notes[step % notes.length],
        type,
        duration: (interval / 1000) * 0.9,
        gain,
        destination: musicGain,
      })
      step++
    }, interval)
  }

  function stopMusic() {
    if (musicTimer) clearInterval(musicTimer)
    musicTimer = null
  }

  const audio = {
    muted: false,
    tone,
    noise,
    sounds,

    /**
     * Plays a named sound.
     *
     * `vary` is the one option worth using everywhere: repetition is what makes
     * a sound effect grating, and a few percent of pitch wander per shot fixes
     * it completely. `audio.play("shoot", { vary: 0.1 })`.
     */
    play(name, config = {}) {
      const sound = sounds[name]
      if (!sound) return
      unlock()
      const { pitch = 1, vary = 0 } = config
      pitchShift = pitch * (1 + (Math.random() - 0.5) * 2 * vary)
      try {
        return sound(config)
      } finally {
        pitchShift = 1
      }
    },

    /** Registers a sound of your own, callable by name like the built-ins. */
    define(name, factory) {
      sounds[name] = factory
      return audio
    },

    get volume() {
      return currentVolume
    },
    set volume(value) {
      currentVolume = value
      ensure()
      if (master && !audio.muted) master.gain.value = value
    },

    mute(value = true) {
      audio.muted = value
      // Restores whatever the volume was set to since, not the initial option.
      if (master) master.gain.value = value ? 0 : currentVolume
      return audio
    },
    toggleMute() {
      return audio.mute(!audio.muted)
    },

    music: { start: startMusic, stop: stopMusic },

    get ready() {
      return unlocked
    },
    unlock,

    dispose() {
      stopMusic()
      context?.close()
      context = null
    },
  }

  return audio
}
